### ISSUE TITLE
When JavaScript is disabled

### ISSUE THREAD

**Issue by nzkks** [nzkks/drmsweb#14]
For some reason JavaScript is **disabled** in the browser, few page elements doesn't show or work.

## Observation:
- Contact information is completely lost
- FontAwesome icons doesn't show. Particularly there is a need in **Bio section**
- Can't expand the individual _skills_ in the **Skills section**
- Download my CV button doesn't show the document links
- _Contact Now_ button doesn't work
- The image and details in each item block within **Testimonial section** doesn't align
- _Technologies Used_ button doesn't work
- _To Top_ button doesn't work

## TODO:
- [x] Mainly create `<noscript>` tags and show below items
- [x] Contact information **must** be shown even when JavaScript is disabled
- [x] **Bio section** to show the social button names 
- [x] Find alternative ways to show all information in the **Skills section**
- [x] Show at least the CV in Word document link
- [x] _Contact Now_ button can be removed or give internal link that points to the new noscript contact content
- [x] Create styles for before and after pseudo classes to contain all information aligned with the item block within **Testimonial section**
- [x] _Technologies_ button can be disabled and show all information
- [x] _To Top_ button to show the name

**Comment by nzkks** [comment]
All done.
